[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  version = "v0.11.7"
  name = "github.com/hashicorp/terraform"

[[constraint]]
  branch = "master"
  name = "github.com/terraform-providers/terraform-provider-aws"

[[constraint]]
  branch = "master"
  name = "github.com/terraform-providers/terraform-provider-tls"

[[constraint]]
  version = "v0.5.0"
  name = "github.com/xenolf/lego"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[override]]
  branch = "master"
  name = "github.com/dnsimple/dnsimple-go"
