[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/terraform"

[[constraint]]
  branch = "master"
  name = "github.com/terraform-providers/terraform-provider-aws"

[[constraint]]
  branch = "master"
  name = "github.com/terraform-providers/terraform-provider-tls"

[[constraint]]
  branch = "master"
  name = "github.com/xenolf/lego"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[override]]
  name = "github.com/mitchellh/copystructure"
  revision = "5af94aef99f597e6a9e1f6ac6be6ce0f3c96b49d"

[[override]]
  name = "github.com/mitchellh/reflectwalk"
  revision = "92573fe8d000a145bfebc03a16bc22b34945867f"
